FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.26-openshift-5.0 AS builder
WORKDIR /go/src/sigs.k8s.io/agent-sandbox
COPY . .
RUN CGO_ENABLED=0 go build \
    -o agent-sandbox-controller ./cmd/agent-sandbox-controller

FROM registry.ci.openshift.org/ocp/4.18:base-rhel9
COPY --from=builder /go/src/sigs.k8s.io/agent-sandbox/agent-sandbox-controller /usr/bin/
USER 65532:65532
ENTRYPOINT ["/usr/bin/agent-sandbox-controller"]
